In [1]:
import pandas as pd
from sklearn.feature_extraction import DictVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
import time
import numpy as np
import os

In [179]:
table1 = pd.read_csv("CSVS/new_no_line/D_BU_A.csv")
table1.drop(table1.columns[-1], axis=1, inplace=True)
table2 = pd.read_csv("CSVS/new_with_line/SOP_j_c_m_BU_A.csv")
table2.drop(table2.columns[0], axis=1, inplace=True)
table2.drop(table2.columns[-1], axis=1, inplace=True)
Trianing_table1 = pd.concat([table1, table2], axis=1)
table3 = pd.read_csv("CSVS/new_with_line/SOP_j_Material_Class.csv")
table3.drop(table3.columns[0], axis=1, inplace=True)
table3.drop(table3.columns[-1], axis=1, inplace=True)
Trianing_table2 = pd.concat([Trianing_table1, table3], axis=1)
table4 = pd.read_csv("CSVS/new_with_line/SOP_j_net_value.csv")
table4.drop(table4.columns[0], axis=1, inplace=True)
table4.drop(table4.columns[-1], axis=1, inplace=True)
Trianing_table3 = pd.concat([Trianing_table2, table4], axis=1)
table5 = pd.read_csv("CSVS/new_with_line/SOP_j_sales_order_num.csv")
table5.drop(table5.columns[0], axis=1, inplace=True)
Trianing_table = pd.concat([Trianing_table3, table5], axis=1)

In [164]:
table1 = pd.read_csv("CSVS/new_no_line/D_BU_A.csv")
table1.drop(table1.columns[-1], axis=1, inplace=True)
table2 = pd.read_csv("CSVS/new_no_line/SOP_j_c_m_BU_A.csv")
table2.drop(table2.columns[-1], axis=1, inplace=True)
Trianing_table1 = pd.concat([table1, table2], axis=1)
table3 = pd.read_csv("CSVS/new_no_line/SOP_j_Material_Class.csv")
table3.drop(table3.columns[-1], axis=1, inplace=True)
Trianing_table2 = pd.concat([Trianing_table1, table3], axis=1)
table4 = pd.read_csv("CSVS/new_no_line/SOP_j_net_value.csv")
table4.drop(table4.columns[-1], axis=1, inplace=True)
Trianing_table3 = pd.concat([Trianing_table2, table4], axis=1)
table5 = pd.read_csv("CSVS/new_no_line/SOP_j_sales_order_num.csv")
Trianing_table = pd.concat([Trianing_table3, table5], axis=1)

In [3]:
Trianing_table = pd.read_csv("All_features/CSVS/new_with_line/D_BU_C.csv")

In [127]:
table1 = pd.read_csv("All_features/CSVS/new_with_line/D_BU_C.csv")
table1.drop(table1.columns[-1], axis=1, inplace=True)
# table2 = pd.read_csv("All_features/CSVS/new_with_line/Zhong_NumItem_STP.csv")
# table2 = pd.read_csv("All_features/CSVS/new_with_line/SOP_NV_Variance.csv")
# table2 = pd.read_csv("All_features/CSVS/new_with_line/SOP_NI_Variance.csv")
# table2 = pd.read_csv("All_features/CSVS/new_with_line/SOP_j_sales_organization.csv")
# table2 = pd.read_csv("All_features/CSVS/new_with_line/SOP_j_sales_order_num.csv")
# table2 = pd.read_csv("All_features/CSVS/new_with_line/SOP_j_Num_Items.csv")
table2 = pd.read_csv("All_features/CSVS/new_with_line/SOP_j_net_value.csv")
table2.drop(table2.columns[0], axis=1, inplace=True)
Trianing_table = pd.concat([table1, table2], axis=1)

In [128]:
# Trianing_table = pd.read_csv("training_variables/D_BU_A_Training.csv")
# Trianing_table = pd.read_csv("training_variables/D_BU_C_Training_new.csv")
# Trianing_table = pd.read_csv("table_to_try/Net_Value.csv")
# Trianing_table = pd.read_csv("table_to_try/SOP_num_Items.csv")
# Trianing_table = pd.read_csv("table_to_try/Final_Variable.csv")
# Trianing_table = pd.read_csv("table_to_try/Final_Variable1.csv")

test_all = Trianing_table[Trianing_table["Reseller"].isna()]
Trianing_table = Trianing_table[~Trianing_table["Reseller"].isna()]

y = Trianing_table['Reseller']
labels = list(Trianing_table.columns.values)
labels.remove("Reseller")
x = Trianing_table[labels]
x_dict_list = x.to_dict(orient='records')
dict_vec = DictVectorizer(sparse=False)
x = dict_vec.fit_transform(x_dict_list)

In [21]:
Trianing_table

Unnamed: 0  V1  V2  V3  V4  V5  V6  V7  V8  V9  ...  V324  V325  V326  \
0              1   0   0   0   0   0   0   0   0   0  ...     0     0     0   
1              2   0   0   0   0   0   0   0   0   0  ...     0     0     0   
2              3   0   0   0   0   0   0   0   0   0  ...     0     0     0   
3              4   0   0   0   0   0   0   0   0   0  ...     0     0     0   
4              5   0   0   0   0   0   0   0   0   0  ...     0     0     0   
...          ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...   ...   ...   ...   
2554        2556   0   0   0   0   0   0   0   0   0  ...     0     0     0   
2555        2557   0   0   0   0   0   0   0   0   0  ...     0     0     0   
2556        2558   0   0   0   0   0   0   0   0   0  ...     0     0     0   
2557        2559   0   0   0   0   0   0   0   0   0  ...     0     0     0   
2559        2561   0   0   0   0   0   0   0   0   0  ...     0     0     0   

      V327  V328  V329  Sales_Order  STP_Ratio  STP_diff_Ratio  Reseller  
0        0     0     0            2   0.000000          0.0000       0.0  
1        0     0     0           11   0.014925          0.0000       0.0  
2        0     0     0            7   1.000000          0.0000       0.0  
3        0     0     0            2   1.000000          0.0000       0.0  
4        0     0     0           57   0.113475          0.0625       0.0  
...    ...   ...   ...          ...        ...             ...       ...  
2554     0     0     0           16   0.230769          0.0000       0.0  
2555     0     0     0            1   0.105590          0.0000       0.0  
2556     0     0     0            6   0.272727          0.0000       0.0  
2557     0     0     0            1   0.000000          0.0000       0.0  
2559     0     0     0            1   1.000000          0.0000       0.0  

[2048 rows x 334 columns]

In [98]:
x.shape

(2048, 331)

In [129]:
# for feat in feat_indices:
# y = dta[:, 329, 0]
# x = dta[:, 0:329, feat].reshape(len(dta), -1)

# 划分训练集和测试集
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1)



In [130]:
def x_train_oversampling(x_train, y_train, ratio):
    x_reseller = x_train[y_train.values==1, :]
    x_nonreseller = x_train[y_train.values==0, :]
    y_reseller = y_train[y_train.values==1]
    y_nonreseller = y_train[y_train.values==0]
    k = round((ratio/(1-ratio))*len(x_nonreseller)/len(x_reseller))
    new_x_train = np.repeat(x_reseller, k, axis=0)
    new_x_train = np.concatenate([new_x_train, x_nonreseller])
    new_y_train = np.concatenate([np.repeat(y_reseller, k), y_nonreseller])
    return new_x_train, new_y_train

In [249]:
np.sum(y_train==1)

119

In [250]:
np.sum(y_train==0)

1724

In [131]:
x_train, y_train = x_train_oversampling(x_train, y_train, ratio=0.25)

In [252]:
np.sum(y_train==1)

714

In [253]:
np.sum(y_train==0)

1724

In [254]:
x_train.shape

(2438, 2321)

In [255]:
y_train.shape

(2438,)

In [132]:
# 决策树分类器
# dec_tree = DecisionTreeClassifier(max_features=100)
dec_tree = DecisionTreeClassifier()
dec_tree.fit(x_train, y_train)

print("*" * 30 + " 准确率 " + "*" * 30)
print(dec_tree.score(x_test, y_test))

****************************** 准确率 ******************************
1.0


In [133]:
def CaculateAcc(reselt, label):
    TP = 0
    TN = 0
    FP = 0
    FN = 0
    for i in range(len(reselt)):
        if(label[i]==1):
            if(reselt[i]==1):
                TP = TP+1
            else: FN =FN+1
        else:
            if(reselt[i]==1):
                FP = FP+1
            else: TN =TN+1
    TPR = TP/(TP+FN)
    TNR = TN/(FP+TN)
    BAC = (TPR+TNR)/2
    return BAC

In [134]:
result = dec_tree.predict(x_test)
label = np.array(y_test)
acc = CaculateAcc(result, label)
acc

1.0

In [135]:
label

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [136]:
result

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [25]:
# 随机森林分类器
# n_jobs: -1表示设置为核心数量
rf = RandomForestClassifier(n_jobs=-1)

# 网格搜索
# n_estimators: 决策树数目
# max_depth: 树最大深度
param = {
    "n_estimators": [120, 200, 300, 500, 800, 1200],
    # "max_depth": [5, 8, 15, 25, 30]
    "max_depth": [5, 10, 11, 12, 15, 20]
}

# 2折交叉验证
search = GridSearchCV(rf, param_grid=param, cv=2)
print("*" * 30 + " 超参数网格搜索 " + "*" * 30)

start_time = time.time()
search.fit(x_train, y_train)

print("耗时：{}".format(time.time() - start_time))
print("最优参数：{}".format(search.best_params_))

# print("*" * 30 + " 准确率 " + "*" * 30)
# print(search.score(x_test, y_test))
# feature_compare.loc[feat, "dt_acc"] = dec_tree.score(x_test, y_test)
# feature_compare.loc[feat, "rf_grid_search"] = search.score(x_test, y_test)



****************************** 超参数网格搜索 ******************************
耗时：42.14023447036743
最优参数：{'max_depth': 20, 'n_estimators': 300}


In [27]:
result = search.predict(x_test)
label = np.array(y_test)
acc = CaculateAcc(result, label)
acc

0.5454545454545454

In [137]:

y_test = test_all['Reseller']
test_labels = list(test_all.columns.values)
test_labels.remove("Reseller")
x_test = test_all[test_labels]
x_test_dict_list = x_test.to_dict(orient='records')
dict_vec = DictVectorizer(sparse=False)
x_test = dict_vec.fit_transform(x_test_dict_list)

In [138]:
len(x_test)

512

In [139]:
result_test = dec_tree.predict(x_test)
result_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [140]:
np.shape(result_test)
result_f = result_test[:]
result_f = result_f.astype(int)
np.shape(result_f)
result_f

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [141]:
path = "result"
if not os.path.exists(path):
    os.mkdir(path)

In [142]:
classification = pd.read_csv("classification.csv")

In [143]:
df = classification.loc[~np.isnan(classification["Test_set_id"]), ["Test_set_id"]]
# df.to_csv("submission_2nd.csv")
df = df.convert_dtypes(int)
df = df.reset_index(drop=True, names=["Test_set_id"])
df.insert(1, column="prediction", value=result_f)
df.to_csv("result/submission.csv", sep=";", index=False)