In [41]:
import pandas as pd
from sklearn.feature_extraction import DictVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
import time
import numpy as np
import os

In [42]:
# Trianing_table = pd.read_csv("training_variables/D_BU_A_Training.csv")
# Trianing_table = pd.read_csv("training_variables/D_BU_C_Training_new.csv")
Trianing_table = pd.read_csv("training_variables/D_BU_C_Training.csv")
# Trianing_table = pd.read_csv("training_variables/d.csv")

y = Trianing_table['Reseller']
labels = list(Trianing_table.columns.values)
labels.remove("Reseller")
x = Trianing_table[labels]
x_dict_list = x.to_dict(orient='records')
dict_vec = DictVectorizer(sparse=False)
x = dict_vec.fit_transform(x_dict_list)

In [43]:
Trianing_table

Unnamed: 0  V1  V2  V3  V4  V5  V6  V7  V8  V9  ...  V321  V322  V323  \
0              1   0   0   0   0   0   0   0   0   0  ...     0     0     0   
1              2   0   0   0   0   0   0   0   0   0  ...     0     0     0   
2              3   0   0   0   0   0   0   0   0   0  ...     0     0     0   
3              4   0   0   0   0   0   0   0   0   0  ...     0     0     0   
4              5   0   0   0   0   0   0   0   0   0  ...     0     0     0   
...          ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...   ...   ...   ...   
2044        2556   0   0   0   0   0   0   0   0   0  ...     0     0     0   
2045        2557   0   0   0   0   0   0   0   0   0  ...     0     0     0   
2046        2558   0   0   0   0   0   0   0   0   0  ...     0     0     0   
2047        2559   0   0   0   0   0   0   0   0   0  ...     0     0     0   
2048        2561   0   0   0   0   0   0   0   0   0  ...     0     0     0   

      V324  V325  V326  V327  V328  V329  Reseller  
0        0     0     0     0     0     0         0  
1        0     0     0     0     0     0         0  
2        0     0     0     0     0     0         0  
3        0     0     0     0     0     0         0  
4        0     0     0     0     0     0         0  
...    ...   ...   ...   ...   ...   ...       ...  
2044     0     0     0     0     0     0         0  
2045     0     0     0     0     0     0         0  
2046     0     0     0     0     0     0         0  
2047     0     0     0     0     0     0         0  
2048     0     0     0     0     0     0         0  

[2049 rows x 331 columns]

In [46]:
x.shape

(2049, 330)

In [47]:
# for feat in feat_indices:
# y = dta[:, 329, 0]
# x = dta[:, 0:329, feat].reshape(len(dta), -1)

# 划分训练集和测试集
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.1)

# 决策树分类器
dec_tree = DecisionTreeClassifier()
dec_tree.fit(x_train, y_train)

print("*" * 30 + " 准确率 " + "*" * 30)
print(dec_tree.score(x_test, y_test))





****************************** 准确率 ******************************
0.9853658536585366


In [48]:
def CaculateAcc(reselt, label):
    TP = 0
    TN = 0
    FP = 0
    FN = 0
    for i in range(len(reselt)):
        if(label[i]==1):
            if(reselt[i]==1):
                TP = TP+1
            else: FN =FN+1
        else:
            if(reselt[i]==1):
                FP = FP+1
            else: TN =TN+1
    TPR = TP/(TP+FN)
    TNR = TN/(FP+TN)
    BAC = (TPR+TNR)/2
    return BAC

In [49]:
result = dec_tree.predict(x_test)
label = np.array(y_test)
acc = CaculateAcc(result, label)
acc

0.9923469387755102

In [50]:
label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [51]:
result

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [ ]:
# 随机森林分类器
# n_jobs: -1表示设置为核心数量
rf = RandomForestClassifier(n_jobs=-1)

# 网格搜索
# n_estimators: 决策树数目
# max_depth: 树最大深度
param = {
    "n_estimators": [120, 200, 300, 500, 800, 1200],
    # "max_depth": [5, 8, 15, 25, 30]
    "max_depth": [5, 10, 11, 12, 15, 20]
}

# 2折交叉验证
search = GridSearchCV(rf, param_grid=param, cv=2)
print("*" * 30 + " 超参数网格搜索 " + "*" * 30)

start_time = time.time()
search.fit(x_train, y_train)

print("耗时：{}".format(time.time() - start_time))
print("最优参数：{}".format(search.best_params_))

# print("*" * 30 + " 准确率 " + "*" * 30)
# print(search.score(x_test, y_test))
# feature_compare.loc[feat, "dt_acc"] = dec_tree.score(x_test, y_test)
# feature_compare.loc[feat, "rf_grid_search"] = search.score(x_test, y_test)



In [22]:
result = search.predict(x_test)
label = np.array(y_test)
acc = CaculateAcc(result, label)
acc

NameError: name 'search' is not defined

In [52]:
Test_table = pd.read_csv("training_variables/D_BU_C_Test.csv")
y_test = Test_table['Reseller']
test_labels = list(Test_table.columns.values)
test_labels.remove("Reseller")
x_test = Test_table[test_labels]
x_test_dict_list = x_test.to_dict(orient='records')
dict_vec = DictVectorizer(sparse=False)
x_test = dict_vec.fit_transform(x_test_dict_list)

In [54]:
len(x_test)

512

In [55]:
result_test = dec_tree.predict(x_test)
result_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [56]:
np.shape(result_test)
result_f = result_test[:]
result_f = result_f.astype(int)
np.shape(result_f)
result_f

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [57]:
path = "result"
if not os.path.exists(path):
    os.mkdir(path)

In [58]:
classification = pd.read_csv("classification.csv")

In [59]:
df = classification.loc[~np.isnan(classification["Test_set_id"]), ["Test_set_id"]]
# df.to_csv("submission_2nd.csv")
df = df.convert_dtypes(int)
df = df.reset_index(drop=True, names=["Test_set_id"])
df.insert(1, column="prediction", value=result_f)
df.to_csv("result/submission.csv", sep=";", index=False)